.PHONY: install

install:
	@forge install eth-infinitism/account-abstraction@v0.7.0 --no-commit
	@forge install cyfrin/foundry-devops@0.2.3 --no-commit
	@forge install openzeppelin/openzeppelin-contracts@v5.0.2 --no-commit