[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"


# for foundry devops
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
