[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/","foundry-devops=lib/foundry-devops"]
ffi = true # enabling this will enable us to run .sh scripts from programs

