[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/-upgradeable/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "foundry-devops/=lib/foundry-devops/",
]
