-include .env

.PHONY: test deploy install

install :
		@forge install cyfrin/foundry-devops@0.2.3 --no-commit
		# @forge install smartcontractkit/chainlink-brownie-contracts@0.6.1 --no-commit
		@forge install openzeppelin/openzeppelin-contracts@v5.0.2 --no-commit
		@forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.0.2 --no-commit
		# @forge install openzeppelin/openzeppelin-contracts@v4.8.3 --no-commit
		# @forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v4.8.3 --no-commit
